### ISSUE TITLE
使用学习原系统，找出原系统中的不足或是你认为可以改进的地方

### ISSUE THREAD

**Issue by teacherpan** [mengyunzhi/schedule#3]
全员（不含组长，以后凡事提到全员的，均不包含组长）任务。

**Comment by moujie1998** [comment]
1.增加批量删除
2.课程与学期关联，一个学期对应多个课程
![image](https://user-images.githubusercontent.com/39559452/46900094-322a8680-cecf-11e8-8b52-51f314cdef54.png)
3.选课管理界面太乱，需要重新设计
